global:
  scrape_interval:      15s
  evaluation_interval:  15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "fist_rules.yml"
  # - "second_rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
    - job_name: "jenkins"
      metric_path: /prometheus
      static_configs:
        -targets:['192.168.1.10:8080']
   

